---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "Governor's Council"
  district_name: "Seventh"
title: "Massachusetts Seventh Governor's Council District"
description: "The Massachusetts Seventh Governor's Council District is currently represented by Democrat Paul M. DePalo of Worcester, who won the seat in 2020 and was reelected in 2022 and 2024. The district covers a large portion of central Massachusetts, including Worcester and numerous surrounding communities, with a population of about 857,000 people."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


