---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "Governor's Council"
  district_name: "Sixth"
title: "Massachusetts Sixth Governor's Council District"
description: "The Massachusetts Sixth Governor's Council District covers several municipalities including Boston, Cambridge, Chelsea, Everett, and other communities in eastern Massachusetts. The district has a population of 899,584. The current incumbent is Terrence W. Kennedy (D-Lynnfield), who has held the seat since 2010 and has been re-elected multiple times, often running unopposed."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


