---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "Governor's Council"
  district_name: "Third"
title: "Massachusetts Third Governor's Council District"
description: "The Massachusetts Third Governor's Council District covers portions of greater Boston, including parts of Boston, Cambridge, Watertown, and surrounding suburbs. The district has been represented by Democrat Marilyn Petitto Devaney of Watertown for many years, but in the upcoming 2024 election, Democrat Mara Dolan of Concord is slated to take the position."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


