---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Barnstable, Dukes and Nantucket"
title: "Massachusetts Barnstable, Dukes and Nantucket State Representative District"
description: "The Barnstable, Dukes and Nantucket State Representative District in Massachusetts is currently represented by Democrat Thomas W. Moakley of Falmouth. The district encompasses Martha's Vineyard, Nantucket, Gosnold, and portions of Falmouth on Cape Cod."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


