---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Eighteenth Essex"
title: "Massachusetts Eighteenth Essex State Representative District"
description: "The Massachusetts Eighteenth Essex State Representative District is currently represented by incumbent Democrat Tram T. Nguyen from Andover. The district includes parts of Andover, Boxford, North Andover, and Tewksbury, covering an area of 57 square miles with a population of approximately 46,164."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


