---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Eighteenth Worcester"
title: "Massachusetts Eighteenth Worcester State Representative District"
description: "The 18th Worcester State Representative District of Massachusetts encompasses the towns of Douglas, Webster, Sutton, as well as parts of Oxford (precincts 1, 4) and Uxbridge (precinct 1). The current incumbent is Republican Joseph D. McKenna from Sutton, who has held the seat since 2014 when he defeated Democrat Mark G. Dowgiewicz. The district is predominantly white (85%) with a poverty rate of 8% and covers approximately 105 square miles."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


