---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Eighteenth Middlesex"
title: "Massachusetts Eighteenth Middlesex State Representative District"
description: "The Massachusetts Eighteenth Middlesex State Representative District is located entirely within Lowell and is currently represented by Democratic incumbent Tara Thorn Hong, who won the seat in the 2024 election with 78% of the vote. The district has a highly diverse population with 62% minority residents and includes 16 precincts in Lowell."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


