---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Eighth Worcester"
title: "Massachusetts Eighth Worcester State Representative District"
description: "The Massachusetts Eighth Worcester State Representative District is currently represented by Republican Michael J. Soter of Bellingham, who has held the seat since winning election in 2018. The district covers portions of Bellingham, Blackstone, Medway, Millville, and Uxbridge, with a population of approximately 43,499 residents."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


