---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Eighth Suffolk"
title: "Massachusetts Eighth Suffolk State Representative District"
description: "The Massachusetts Eighth Suffolk State Representative District is currently represented by Democratic incumbent Jay D. Livingstone of Boston, who has held the seat since winning a special election in 2013. The district is located entirely within Boston, covering portions of the city across 18 precincts. It is a compact urban district with an area of just 1 square mile and a population of 41,784."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


