---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Eleventh Middlesex"
title: "Massachusetts Eleventh Middlesex State Representative District"
description: "This district is located entirely in Newton, Massachusetts, covering 16 precincts within the city. The current representative is Amy Mah Sangiolo (D-Newton), who won the most recent election in November 2024 with 81% of the vote against Republican challenger Vladislav S. Yanovsky. Prior to Sangiolo, Kay S. Khan (D-Newton) represented the district for many years, often running unopposed."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


