---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Eleventh Bristol"
title: "Massachusetts Eleventh Bristol State Representative District"
description: "The Massachusetts Eleventh Bristol State Representative District covers parts of New Bedford and is currently represented by Democratic incumbent Christopher Hendricks of New Bedford. The district has been consistently held by Democrats, with Hendricks winning uncontested elections since 2018."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


