---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Fifteenth Worcester"
title: "Massachusetts Fifteenth Worcester State Representative District"
description: "The Massachusetts Fifteenth Worcester State Representative District is located entirely within Worcester, including parts of several precincts. It is currently represented by Democratic incumbent Mary S. Keefe of Worcester, who has held the seat since 2012 and has run unopposed in most recent elections."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


