---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Fifth Suffolk"
title: "Massachusetts Fifth Suffolk State Representative District"
description: "The Fifth Suffolk State Representative District is located in Boston, encompassing parts of neighborhoods including Dorchester and Roxbury. The district is currently represented by Democratic incumbent Christopher J. Worrell of Boston, who was first elected in 2022. The district is majority-minority with 92% of residents identifying as non-white, particularly Black (48%) and Hispanic (29%) populations."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


