---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Fifteenth Suffolk"
title: "Massachusetts Fifteenth Suffolk State Representative District"
description: "The Massachusetts Fifteenth Suffolk State Representative District is a legislative district located in Boston, covering 19 precincts across multiple Boston neighborhoods. The current incumbent is Democratic Representative Samantha Montaño of Boston, who has served since 2022 after winning uncontested elections in both 2022 and 2024."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


