---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Fifteenth Norfolk"
title: "Massachusetts Fifteenth Norfolk State Representative District"
description: "The Massachusetts Fifteenth Norfolk State Representative District is located entirely in Brookline, encompassing 13 precincts. The current incumbent is Democratic Representative Tommy Vitolo of Brookline, who has represented the district since 2018 and has run unopposed in all of his elections."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


