---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "First Norfolk"
title: "Massachusetts First Norfolk State Representative District"
description: "The First Norfolk State Representative District in Massachusetts covers parts of Quincy and Randolph, comprising about 49,065 residents across 13 square miles. The district is currently represented by Bruce J. Ayers, a Democrat from Quincy who has been consistently reelected without opposition since 2006, with his most recent contested election being in 2004."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


