---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "First Plymouth"
title: "Massachusetts First Plymouth State Representative District"
description: "The Massachusetts First Plymouth State Representative District is represented by incumbent Michelle L. Badger (Democrat) who won the most recent election in 2024. The district is located in Plymouth, encompassing 13 precincts in the town, with a predominantly white population (91%) and covers approximately 93 square miles."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


