---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "First Franklin"
title: "Massachusetts First Franklin State Representative District"
description: "The Massachusetts First Franklin State Representative District is located in western Massachusetts, covering all or part of 18 cities/towns including portions of Greenfield and communities like Deerfield, Montague, and Sunderland. The current incumbent is Democratic Representative Natalie M. Blais of Deerfield, who has represented the district since 2018 and has run unopposed in all her elections."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


