---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Fourteenth Norfolk"
title: "Massachusetts Fourteenth Norfolk State Representative District"
description: "The Massachusetts Fourteenth Norfolk State Representative District is represented by incumbent Democrat Alice Hanlon Peisch of Wellesley. The district includes parts of Lincoln, Wellesley, and Weston, covering about 34 square miles with a population of approximately 44,653 people."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


