---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Fourth Barnstable"
title: "Massachusetts Fourth Barnstable State Representative District"
description: "The Massachusetts Fourth Barnstable State Representative District covers seven Cape Cod towns including Chatham, Eastham, Harwich, Orleans, Provincetown, Truro, and Wellfleet. The current incumbent is Democrat Sarah K. Peake of Provincetown, who has held the seat since 2007 and has run unopposed in most recent elections."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


