---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Fourth Worcester"
title: "Massachusetts Fourth Worcester State Representative District"
description: "The Massachusetts Fourth Worcester State Representative District encompasses the city of Leominster. The district is currently represented by incumbent Democrat Natalie Higgins of Leominster, who has held the seat since 2016 and most recently won reelection in 2024 with 58% of the vote against Republican challenger Salvatore Perla."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


