---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Fourteenth Worcester"
title: "Massachusetts Fourteenth Worcester State Representative District"
description: "The Fourteenth Worcester district includes West Boylston and several precincts in Worcester. The district is currently represented by Democratic incumbent James J. O'Day of West Boylston, who has held the seat since 2007 and has run unopposed in most recent elections."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


