---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Fourteenth Bristol"
title: "Massachusetts Fourteenth Bristol State Representative District"
description: "The Massachusetts Fourteenth Bristol State Representative District is currently represented by Democrat Adam J. Scanlon of North Attleborough, who was most recently reelected in 2024. The district encompasses portions of Attleboro, Mansfield, and North Attleborough with a population of approximately 42,608."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


