---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Nineteenth Middlesex"
title: "Massachusetts Nineteenth Middlesex State Representative District"
description: "The Massachusetts Nineteenth Middlesex State Representative District encompasses parts of Tewksbury and Wilmington, covering 27 square miles with a population of 40,440. The district is currently represented by incumbent Democratic Representative David Allen Robertson of Wilmington, who won reelection in 2024 with 53% of the vote against Republican and third-party challengers."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


