---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Ninth Suffolk"
title: "Massachusetts Ninth Suffolk State Representative District"
description: "The Massachusetts Ninth Suffolk State Representative District is currently represented by Democratic incumbent John Francis Moran, who won a special election in 2023 with 100% of the vote. The district is located entirely in Boston, encompassing parts of 18 precincts within the city, and has a diverse population with 56% minority residents and 44% white residents."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


