---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Second Essex"
title: "Massachusetts Second Essex State Representative District"
description: "The Second Essex State Representative District in Massachusetts is currently represented by Kristin E. Kassner, a Democrat from Hamilton, who won a close race in 2022 and was reelected in 2024. The district encompasses Georgetown, Hamilton, Ipswich, Newbury, Rowley, and part of Topsfield, covering 112 square miles with a population of 46,046."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


