---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Second Barnstable"
title: "Massachusetts Second Barnstable State Representative District"
description: "The Second Barnstable district is represented by incumbent Democrat Kip A. Diggs of Barnstable. The district includes most of Barnstable and portions of Yarmouth on Cape Cod, covering an area of 46 square miles with a population of approximately 44,853 residents."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


