---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Second Franklin"
title: "Massachusetts Second Franklin State Representative District"
description: "The Massachusetts Second Franklin State Representative District is currently represented by Susannah M. Whipps, an Independent from Athol who has held the seat since 2015. The district encompasses parts of central/north-central Massachusetts including the towns of Athol, Erving, Gill, parts of Greenfield, Northfield, Orange, Phillipston, Royalston, Warwick, and a precinct of Winchendon."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


