---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Seventeenth Worcester"
title: "Massachusetts Seventeenth Worcester State Representative District"
description: "The 17th Worcester State Representative District in Massachusetts includes parts of Leicester and Worcester. It is currently represented by Democrat David Henry Argosky LeBoeuf from Worcester, who has held the seat since 2018 and ran unopposed in the 2024 election."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


