---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Sixth Hampden"
title: "Massachusetts Sixth Hampden State Representative District"
description: "The Massachusetts Sixth Hampden State Representative District includes portions of Agawam, Chicopee, West Springfield, and Westfield, with a population of approximately 43,764. The current incumbent is Democratic Representative Michael J. Finn of West Springfield, who has held the seat since 2010 and has run unopposed in most recent elections."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


