---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Tenth Bristol"
title: "Massachusetts Tenth Bristol State Representative District"
description: "The Massachusetts Tenth Bristol State Representative District is located in southeastern Massachusetts, encompassing all of Fairhaven, Marion, and Mattapoisett, as well as portions of Acushnet, New Bedford, and Rochester. The current representative is Democrat Mark David Sylvia of Fairhaven, who won the seat in the 2024 election with 53% of the vote against Republican Joseph M. Pires."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


