---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Thirty-Seventh Middlesex"
title: "Massachusetts Thirty-Seventh Middlesex State Representative District"
description: "The Thirty-Seventh Middlesex State Representative District in Massachusetts is currently represented by Democrat Danillo A. Sena of Acton. The district includes portions of Acton, as well as Ayer, Boxborough, part of Groton, Harvard, and Shirley, covering an area of 86 square miles in north-central Massachusetts."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


