---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Thirteenth Middlesex"
title: "Massachusetts Thirteenth Middlesex State Representative District"
description: "This legislative district encompasses parts of Concord, Lincoln, Marlborough, Sudbury, and Wayland. The current incumbent is Democrat Carmine Lawrence Gentile from Sudbury, who has represented the district since 2014 and most recently won reelection in 2024 with 74% of the vote."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


