---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Thirty-Third Middlesex"
title: "Massachusetts Thirty-Third Middlesex State Representative District"
description: "The Thirty-Third Middlesex State Representative District is located entirely within Malden, covering 18 precincts of the city. It is currently represented by Democrat Steven Ultrino of Malden, who has won every election since 2014, running unopposed in the most recent elections."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


