---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Thirty-Sixth Middlesex"
title: "Massachusetts Thirty-Sixth Middlesex State Representative District"
description: "The Thirty-Sixth Middlesex State Representative District in Massachusetts includes the towns of Dracut and Tyngsborough. It is currently represented by Democrat Colleen M. Garry of Dracut, who has held this seat since at least 2002 and has won several elections, sometimes unopposed."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


