---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Third Barnstable"
title: "Massachusetts Third Barnstable State Representative District"
description: "The Massachusetts Third Barnstable State Representative District covers parts of Bourne and Falmouth, as well as Mashpee, with a total population of 44,429. The district is currently represented by Republican David T. Vieira of Falmouth, who has held the seat since defeating Democrat Matthew Patrick in 2010 and most recently won reelection in 2024."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


