---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Thirteenth Essex"
title: "Massachusetts Thirteenth Essex State Representative District"
description: "The Thirteenth Essex State Representative District in Massachusetts covers parts of Danvers, Middleton, Peabody, Topsfield, and Wenham, spanning 30 square miles with a population of 44,833. The district is predominantly white (88%) with a 4% poverty rate and 36% college-educated population. It is currently represented by Democratic incumbent Sally P. Kerans of Danvers, who reclaimed the seat in 2020 after previously serving in the early 1990s."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


