---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Thirteenth Norfolk"
title: "Massachusetts Thirteenth Norfolk State Representative District"
description: "The Massachusetts Thirteenth Norfolk State Representative District includes all of Dover, parts of Medfield, and all of Needham, covering a predominantly white, affluent area with low poverty rates. The district is currently represented by Joshua Tarsky, a Democrat from Needham, who won the seat in 2024 with 61% of the vote after longtime Democratic representative Denise C. Garlick held the position from 2010 to 2022."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


