---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Third Berkshire"
title: "Massachusetts Third Berkshire State Representative District"
description: "The Massachusetts Third Berkshire State Representative District covers 18 towns in western Massachusetts including Great Barrington, Lenox, and several other Berkshire County communities. The district is currently represented by Democrat Leigh Susan Davis of Great Barrington, who won the seat in 2024 with 57% of the vote against independent candidate Marybeth F. Mitts."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


