---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Twelfth Bristol"
title: "Massachusetts Twelfth Bristol State Representative District"
description: "The Massachusetts Twelfth Bristol State Representative District covers Berkley, Lakeville, parts of Middleborough (precincts 2, 4, 5, 7), and parts of Taunton (precincts 3-A, 3-B, 4-A, 4-B). The current incumbent is Norman J. Orrall, a Republican from Lakeville, who has held the seat since winning election in 2018."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


