---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Twelfth Suffolk"
title: "Massachusetts Twelfth Suffolk State Representative District"
description: "The Massachusetts Twelfth Suffolk State Representative District is currently represented by Democrat Brandy Fluker Oakley of Boston who has held the seat since 2020. The district encompasses parts of Boston and Milton, with a predominantly minority population (83%) that includes portions of the Dorchester, Mattapan, and Hyde Park neighborhoods."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


