---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Twelfth Worcester"
title: "Massachusetts Twelfth Worcester State Representative District"
description: "The 12th Worcester State Representative District in Massachusetts is currently represented by Democratic incumbent Meghan Kilcoyne of Clinton. The district encompasses Berlin, Boylston, Clinton, Lancaster, Sterling, and part of Northborough, covering a mostly white, suburban/rural area in central Massachusetts."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


