---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Twelfth Norfolk"
title: "Massachusetts Twelfth Norfolk State Representative District"
description: "The Massachusetts Twelfth Norfolk State Representative District is represented by incumbent Democrat John H. Rogers of Norwood, who has held the seat since at least 1992. The district covers the town of Norwood and several precincts in Walpole, with a population of about 44,415 people."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


