---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Twelfth Hampden"
title: "Massachusetts Twelfth Hampden State Representative District"
description: "The Massachusetts Twelfth Hampden State Representative District is currently represented by incumbent Democrat Angelo J. Puppolo, Jr. of Springfield. The district includes parts of East Longmeadow, Monson, Springfield, and Wilbraham, with a population of approximately 44,026 people."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


