---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Twenty-Second Middlesex"
title: "Massachusetts Twenty-Second Middlesex State Representative District"
description: "This district covers the town of Billerica and is currently represented by Republican incumbent Marc T. Lombardo, who has held the seat since 2010 and won his most recent election in 2022 with 54% of the vote against Democratic challenger Teresa Nicole English."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


