---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Twentieth Middlesex"
title: "Massachusetts Twentieth Middlesex State Representative District"
description: "The Massachusetts Twentieth Middlesex State Representative District is currently represented by incumbent Republican Bradley H. Jones, Jr. of North Reading, who has held the seat continuously since at least 2002. The district includes parts of Lynnfield, Middleton, North Reading, and Reading, covering an area of 41 square miles with a population of approximately 44,611."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


