---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Twenty-Fifth Middlesex"
title: "Massachusetts Twenty-Fifth Middlesex State Representative District"
description: "The Massachusetts Twenty-Fifth Middlesex State Representative District is located entirely in Cambridge and is currently represented by Democratic incumbent Marjorie C. Decker. The district has been consistently held by Democrats, with Rep. Decker winning her elections with overwhelming majorities, often running unopposed."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


