---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Twenty-Third Middlesex"
title: "Massachusetts Twenty-Third Middlesex State Representative District"
description: "The Twenty-Third Middlesex State Representative District in Massachusetts includes portions of Arlington (15 precincts) and Medford (3 precincts). The current incumbent is Sean Garballey (Democrat) from Arlington, who has held the seat since winning a special election in March 2008 and has run unopposed in most subsequent elections."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


