---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Twenty-Seventh Middlesex"
title: "Massachusetts Twenty-Seventh Middlesex State Representative District"
description: "The Massachusetts Twenty-Seventh Middlesex State Representative District is located entirely within Somerville and is currently represented by Democrat Erika Uyterhoeven, who has held the seat since 2021. The district is highly Democratic, with the incumbent typically winning without Republican opposition."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


