---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Twenty-Ninth Middlesex"
title: "Massachusetts Twenty-Ninth Middlesex State Representative District"
description: "The Massachusetts Twenty-Ninth Middlesex State Representative District is currently represented by incumbent Democrat Steven C. Owens of Watertown. The district encompasses parts of Cambridge (8 precincts) and all of Watertown (8 precincts), covering approximately 5 square miles with a population of 43,429."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


