---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Representative"
  district_name: "Twenty-Eighth Middlesex"
title: "Massachusetts Twenty-Eighth Middlesex State Representative District"
description: "The Twenty-Eighth Middlesex State Representative District is located entirely within the city of Everett, Massachusetts. The current incumbent is Democratic State Representative Joseph W. McGonagle, Jr. of Everett, who has represented the district since 2014.
"
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


