---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "U.S. House"
  district_name: "Eighth"
title: "Massachusetts Eighth U.S. House District"
description: "This district, which includes parts of Boston and several towns south of the city, has been represented by incumbent Democratic Representative Stephen F. Lynch of Boston since 2013. It covers portions of Boston and surrounding communities including Quincy, Brockton, and other municipalities in eastern Massachusetts."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


