---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "U.S. House"
  district_name: "Fifth"
title: "Massachusetts Fifth U.S. House District"
description: "This Massachusetts Fifth U.S. House District is currently represented by incumbent Democratic Representative Katherine M. Clark from Revere. The district covers eastern Massachusetts communities including parts of Cambridge, Arlington, Framingham, Lexington, Malden, Medford, and several other municipalities in the greater Boston area."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


