---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "U.S. House"
  district_name: "Fourth"
title: "Massachusetts Fourth U.S. House District"
description: "The Massachusetts Fourth U.S. House District is currently represented by Democratic incumbent Jake Auchincloss of Newton, who has held the seat since 2021. The district covers 710 square miles in eastern Massachusetts, including portions of Norfolk, Bristol, and Middlesex counties, with a population of approximately 778,000 residents."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


