---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "U.S. House"
  district_name: "Second"
title: "Massachusetts Second U.S. House District"
description: "This district is currently represented by Democratic incumbent James P. McGovern from Worcester, who has been consistently winning elections with 65-69% of the vote in recent years. The district covers a large portion of central Massachusetts including Worcester, Northampton, and numerous towns in western and central Massachusetts, encompassing both urban and rural areas."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


