---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "U.S. House"
  district_name: "Third"
title: "Massachusetts Third U.S. House District"
description: "The Massachusetts Third U.S. House District is represented by incumbent Lori Loureiro Trahan, a Democrat from Westford. The district covers portions of northeastern Massachusetts including parts of Middlesex, Worcester, and Essex counties, encompassing communities such as Acton, Lowell, Fitchburg, and portions of Billerica and Groton."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


