---
title: About
description: "About the mapoli Massachusetts Legislative District Atlas, its data sources, and how to get in touch."
format:
  html:
    page-layout: full
---

The [mapoli](index.html) Legislative District Atlas has overview pages
with a map and comparative demographics for Massachusetts State
Representative, State Senate, Governor's Council, and U.S. House
districts and individual pages for the 217 individual districts with a
map, overview, election results, and demographics for each district.

The site was created and is maintained by Brent Benson who has a
passion for collecting, combining, and analyzing data, with a
particular interest in Massachusetts politics and policy. You can get
in touch with Brent on
[Bluesky](https://bsky.app/profile/brentwbenson.org),
[Threads](https://www.threads.com/@bwbensonjr), or by email using the
address `brent` at `mapoli.us`.

The primary sources for the data in the district atlas are:

- Election results data from the invaluable
  [electionstats.state.ma.us](https://electionstats.state.ma.us/) site
  created by [Adam Friedman of Civera](https://civera.com/team/) and
  supported by the [Secretary of the
  Commonwealth](https://www.sec.state.ma.us/).
- GIS mapping and geometry data from
  (MassGIS)(https://www.mass.gov/orgs/massgis-bureau-of-geographic-information).
- Demographic data from [U.S. Census Bureau](https://www.census.gov/).

