---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Senate"
  district_name: "Bristol and Norfolk"
title: "Massachusetts Bristol and Norfolk State Senate District"
description: "The Massachusetts Bristol and Norfolk State Senate District is currently represented by Democratic incumbent Paul R. Feeney from Foxborough. The district covers parts of southeastern Massachusetts including Attleboro, Canton, Foxborough, Mansfield, North Attleborough, Norton, and Sharon."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


