---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Senate"
  district_name: "First Essex and Middlesex"
title: "Massachusetts First Essex and Middlesex State Senate District"
description: "The Massachusetts First Essex and Middlesex State Senate District is represented by longtime Republican incumbent Bruce E. Tarr of Gloucester, who has held the seat since 1994. The district covers multiple communities across northeastern Massachusetts including parts of Essex and Middlesex counties, with a predominantly white (90%) population of 176,199 residents."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


