---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Senate"
  district_name: "First Bristol and Plymouth"
title: "Massachusetts First Bristol and Plymouth State Senate District"
description: "The Massachusetts First Bristol and Plymouth State Senate District encompasses Fall River, Freetown, Lakeville, Rochester, Somerset, Swansea, and Westport, covering 237 square miles with a population of 171,292. The current incumbent is Democratic State Senator Michael J. Rodrigues of Westport, who has represented the district since 2010 and ran unopposed in the 2024 election."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


