---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Senate"
  district_name: "Hampden"
title: "Massachusetts Hampden State Senate District"
description: "The Massachusetts Hampden State Senate District is currently represented by Adam Gomez (D-Springfield), who has been in office since 2020 and was most recently reelected unopposed in 2022. The district covers parts of Springfield and Chicopee, with a diverse population that is 69% minority (48% Hispanic, 16% Black) and has a 25% poverty rate."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


