---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Senate"
  district_name: "Hampshire, Franklin and Worcester"
title: "Massachusetts Hampshire, Franklin and Worcester State Senate District"
description: "The Massachusetts Hampshire, Franklin and Worcester State Senate District is currently represented by incumbent Jo Comerford (D-Northampton) who has held the seat since 2018 and has run unopposed in recent elections. The district spans 25 municipalities in western Massachusetts including Amherst, Northampton, Greenfield, and surrounding towns, covering 783 square miles with approximately 160,574 residents."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


