---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Senate"
  district_name: "Hampden, Hampshire and Worcester"
title: "Massachusetts Hampden, Hampshire and Worcester State Senate District"
description: "This state senate district includes parts of Chicopee and Springfield, as well as several complete towns including Belchertown, East Longmeadow, Granby, Hampden, Longmeadow, Ludlow, Palmer, South Hadley, Warren, and Wilbraham. The district is currently represented by Democrat Jacob R. Oliveira of Ludlow, who first won the seat in 2022 with 56% of the vote and is running unopposed in 2024."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


