---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Senate"
  district_name: "Norfolk, Plymouth and Bristol"
title: "Massachusetts Norfolk, Plymouth and Bristol State Senate District"
description: "This is a Massachusetts state senate district with an incumbent Democrat, William J. Driscoll, Jr. of Milton (who appears to be replacing Walter F. Timilty, Jr.). The district includes parts of Braintree and Randolph, as well as the towns of Bridgewater, Easton, Milton, Stoughton, and West Bridgewater, covering an area of 120 square miles with a population of 166,202."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


