---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Senate"
  district_name: "Norfolk and Suffolk"
title: "Massachusetts Norfolk and Suffolk State Senate District"
description: "The Norfolk and Suffolk State Senate District in Massachusetts is represented by incumbent Michael F. Rush (D-Boston), who has run unopposed since at least 2012. The district encompasses parts of Boston as well as Dedham, Norwood, Walpole, and Westwood, with a population of 183,656 that is predominantly white (69%) with 31% minority residents."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


