---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Senate"
  district_name: "Norfolk, Worcester and Middlesex"
title: "Massachusetts Norfolk, Worcester and Middlesex State Senate District"
description: "The Norfolk, Worcester and Middlesex State Senate District is currently represented by Democratic incumbent Rebecca L. Rausch of Needham, who won re-election in 2024 with 59% of the vote. The district spans 11 communities across three counties including Bellingham, Dover, Franklin, Medfield, Milford, Millis, Needham, Norfolk, Plainville, Sherborn, and Wrentham."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


