---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Senate"
  district_name: "Plymouth and Barnstable"
title: "Massachusetts Plymouth and Barnstable State Senate District"
description: "The Massachusetts Plymouth and Barnstable State Senate District covers towns including Bourne, Falmouth, Kingston, Mashpee, Pembroke, Plymouth, Plympton, and Sandwich. The district is currently represented by Democrat Susan Lynn Moran of Falmouth, who won her seat in the 2022 election with 56% of the vote."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


