---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Senate"
  district_name: "Second Essex and Middlesex"
title: "Massachusetts Second Essex and Middlesex State Senate District"
description: "The Massachusetts Second Essex and Middlesex State Senate District is represented by incumbent Democrat Barry R. Finegold of Andover. The district spans portions of Essex and Middlesex counties, including Amesbury, Andover, parts of Haverhill, Merrimac, North Andover, Tewksbury, and Wilmington."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


