---
format:
  html:
    page-layout: full
execute:
  echo: false
  warning: false
params:
  office_name: "State Senate"
  district_name: "Third Middlesex"
title: "Massachusetts Third Middlesex State Senate District"
description: "The Massachusetts Third Middlesex State Senate District is represented by incumbent Democrat Michael J. Barrett of Lexington, who has served since 2012 and has run unopposed in the last four elections. The district encompasses parts of Middlesex County, including Bedford, Carlisle, Chelmsford, Concord, parts of Lexington, Lincoln, Waltham, and Weston."
---

```{r}
library(here)
source(here("website/_gen/legislative_info.R"))
```

```{r}
dist_map <- district_map(params$office_name, params$district_name)
tmap_leaflet(dist_map)
```

<br/>

::: {.panel-tabset}

## Demographics

```{r}
district_demographics(params$office_name, params$district_name)
```

## Cities/Towns

```{r}
district_precincts(params$office_name, params$district_name)
```

:::

## Elections

```{r}
district_elections(params$office_name, params$district_name)
```


